#!/usr/bin/sh bash

alias gs='git status'
alias ga='git add'
alias ga.='git add .'
alias gb='git branch'
alias gc='git commit -m'
alias gd='git diff'
alias gm='git merge'
alias go='git checkout'
alias gps='git push'
alias gpl='git pull'
alias gk='gitk --all&'
alias gx='gitx --all'
alias got='git'
alias get='git'
alias st='npm start'
alias bd='npm run build'
alias dev='npm run dev'
alias fmt='npm run format'
